### ISSUE TITLE
gorm.Model has ID

### ISSUE THREAD

**Issue by sixcolors** [kuki1029/TODO_App#1]
The gorm model already has ID, so your model used for migration doesn't need to include anything in the gorm.Model.

The DTO should not include the gorm.Model, so ID should be defined on that model.

https://github.com/kuki1029/TODO_App/blob/a2282fbf77b8c4004f0a97195bed3ce5b586091a/models/taskModel.go#L11

https://gorm.io/docs/models.html#gorm-Model

**Comment by kuki1029** [comment]
This was resolved in #8 .
