### ISSUE TITLE
ID in gorm.Model primaryKey uint does not need AUTOINCREMENT

### ISSUE THREAD

**Issue by sixcolors** [kuki1029/TODO_App#2]
https://github.com/kuki1029/TODO_App/blob/a2282fbf77b8c4004f0a97195bed3ce5b586091a/models/userModel.go#L10

ID in gorm.Model primaryKey uint does not need AUTOINCREMENT... also the field tag is `autoIncrement`

https://gorm.io/docs/models.html#Fields-Tags

**Comment by sixcolors** [comment]
If you want assign an ID value to a new user pointer without doing it on a separate line just do:
```
u := &user{Model: gorm.Model{ID: id}, Name: "Joe",}
```

**Comment by kuki1029** [comment]
This was also resolved in #8 when removing ID from the user struct as it contained gorm model.
